name: dart_plex_api
version: 0.1.0
author: Jacob Shuman <jacob.shuman7@gmail.com>
description: An unofficial wrapper for the plex web api.
repository: https://github.com/jacob-shuman/dart_plex_api

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
