name: dart_plex_api
version: 0.1.0
author: Jacob Shuman <jacob.shuman7@gmail.com>
description: An unofficial wrapper for the plex web api.
homepage: https://github.com/jacob-shuman/dart_plex_api
repository: https://github.com/jacob-shuman/dart_plex_api

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
