name: dart_plex_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/jacob-shuman/dart_plex_api
author: Jacob Shuman <jacob.shuman7@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
